### ISSUE TITLE
Title message has text colour black on black background

### ISSUE THREAD

**Issue by schrepfler** [jobrunr/website#1]
The following phrase
**Open and free for commercial use.Alternative for Spring Batch and Quartz Scheduler. Hangfire for Java.**
has 
**Alternative for Spring Batch and Quartz Scheduler. Hangfire for Java.** 
in black so it's not really visible.

**Comment by rdehuyss** [comment]
Sorry, just saw your issue now... Yes, that's on purpose :smile: . I did not want it to be really readable but adding it in the H1 of the site aids for google search.

Nice catch though, you're the first to say something about it!
