### ISSUE TITLE
en/documentation/configuration/spring: dash instead of underscore

### ISSUE THREAD

**Issue by bangert** [jobrunr/website#12]
Thanks for jobrunr!

https://github.com/jobrunr/website/blob/master/content/en/documentation/configuration/spring/_index.md:

should it be 
org.jobrunr.database.skip-create=false
org.jobrunr.database.table-prefix

instead of 

org.jobrunr.database.skip_create=false
org.jobrunr.database.table_prefix

(underscores replaced with dashes/hypen)?

**Comment by rdehuyss** [comment]
Fixed!
