### ISSUE TITLE
Incorrect codeblock

### ISSUE THREAD

**Issue by qjansen-xti** [jobrunr/website#4]
I can't seem to find the codeblock in the website repo, but it's the one on the very bottom of this [page](https://www.jobrunr.io/en/documentation/background-methods/#via-a-jobrequest).

More specifically this part:
```
@Component
public class MyJobRequestHandler implements JobRequestHandler {
...
  }
}
```

I think it should be:
```
@Component
public class MyJobRequestHandler implements JobRequestHandler<MyJobRequest> {
...
  }
}
```

**Comment by rdehuyss** [comment]
Resolved
